import os
os.environ.setdefault('QT_QPA_PLATFORM','offscreen')
os.environ.setdefault('QSG_RHI_BACKEND','software')
from pathlib import Path
import sys,struct,time,unittest
from queue import Queue
from unittest.mock import patch
sys.path.insert(0,str(Path(__file__).resolve().parents[1]))
from PySide6.QtWidgets import QApplication
from PySide6.QtQuickControls2 import QQuickStyle
from PySide6.QtQml import QQmlApplicationEngine
from PySide6.QtCore import QUrl,QEventLoop,QTimer
from PySide6.QtGui import QFontDatabase
from wire_protocol import *
from dac_calibration import CurveCalibration,TARGETS_MV,LEGACY_TARGETS_MV
from xin_power_qt import Bridge,ProbeScanThread
from readable_log import format_frame
QQuickStyle.setStyle('Basic');APP=QApplication.instance() or QApplication([])
for fn in ('msyh.ttc','consola.ttf','seguisym.ttf','segoeui.ttf'):QFontDatabase.addApplicationFont('C:/Windows/Fonts/'+fn)

class FakePort:
    def __init__(self):self.buffer=bytearray();self.writes=[];self.is_open=True
    @property
    def in_waiting(self):return len(self.buffer)
    def write(self,data):self.writes.append(data)
    def read(self,n):data=bytes(self.buffer[:n]);del self.buffer[:n];return data
    def flush(self):pass
    def reset_input_buffer(self):self.buffer.clear()
    def close(self):self.is_open=False

class ProtocolTests(unittest.TestCase):
    def test_firmware_hex_version_and_vectors(self):
        from firmware_image import load_firmware
        path=Path(__file__).resolve().parents[2]/'02_Application/MDK-ARM/Objects/XIN_Power.hex'
        if not path.exists():self.skipTest('请先构建 Keil APP')
        image=load_firmware(path,'6.2.3')
        self.assertGreater(image.size,100000);self.assertIn(b'proto=5',image.data)

    def test_fragmentation_crc_noise_timeout(self):
        data=encode(1,123,b'\x10\xff\xff');p=Parser();result=[]
        for byte in b'noise'+data:result.extend(p.feed(bytes([byte]),now=1))
        self.assertEqual(result,[Packet(1,123,b'\x10\xff\xff')])
        corrupt=bytearray(data);corrupt[-1]^=1
        self.assertEqual(p.feed(corrupt+data,now=1),result)
        self.assertGreater(p.bad_frames,0)
        p.feed(data[:7],now=1);self.assertEqual(p.feed(data,now=2),result)
        self.assertLessEqual(len(p.buffer),458)
    def test_real_c_vectors(self):
        # Generated by the real firmware handlers and DMA TX ring harness.
        location=Path(__file__).resolve().parents[2]/'tests/wire_vectors_620.bin'
        packets=Parser().feed(location.read_bytes());frames=[decode(p) for p in packets]
        self.assertTrue(frames)
        info=next(f for f in frames if f.kind=='info')
        self.assertEqual(info.values['fw'],'6.2.3');self.assertEqual(info.values['ota'],'CONFIRMED')
        self.assertEqual(info.values['sample_ms'],'2');self.assertEqual(info.values['vmin'],'3200')
        self.assertEqual(info.values['telemetry_ms'],'40')
        tel=next(f for f in frames if f.kind=='telemetry');self.assertEqual(tel.values['setv'],'3300')
        self.assertTrue(any(f.kind=='curve' and f.values['schema']=='5' for f in frames))
        self.assertTrue(any(f.kind=='error' and f.values['reason']=='SEQUENCE_CONFLICT' for f in frames))
        self.assertTrue(any(f.kind=='ack' and f.values['cmd']=='CAL_POINT_CAPTURE' for f in frames))
        self.assertEqual(len(next(p.payload for p in packets if p.type==5)),77)
    def test_same_sequence_retry_and_duplicate_reply(self):
        port=FakePort();s=SerialSession(port,True);s.send('CAL POINT STEP -1');wire=port.writes[-1]
        s.pending[3]=0;s.poll();self.assertEqual(port.writes[-1],wire)
        seq=s.pending[0];ack=encode(2,seq,b'\x10DAC_APPLIED');port.buffer.extend(ack+ack)
        self.assertEqual(len(s.poll()),1);self.assertIsNone(s.pending)
        # Multiple distinct diagnostic packets in one reply are retained.
        s.send('DIAG');seq=s.pending[0];port.buffer.extend(encode(11,seq,b'USB')+encode(11,seq,b'BT'))
        self.assertEqual(len(s.poll()),2)
    def test_commands_payload_and_upgrade_adapter(self):
        self.assertEqual(command_payload('CAL SET V 1000000 3',0),b'\x09'+struct.pack('<ii',1000000,3))
        self.assertEqual(command_payload('FW DATA 192 A55A00',0),b'\x20'+struct.pack('<I',192)+b'\xa5\x5a\0')
        self.assertEqual(command_payload('CAL POINT GET 15',0),b'\x0e\x0f\0')
        port=FakePort();s=SerialSession(port,True);s.write(b'FW STATUS\r\n')
        port.buffer.extend(encode(2,s.sequence,b'\x1e192/512/0'))
        self.assertIn(b'@ACK,cmd=FW_STATUS,detail=192/512/0',s.readline())
    def test_fault_packet_and_chinese_log(self):
        data=struct.pack('<IBBHHHHHi i I h B IIH'.replace(' ',''),1,6,1,3300,2638,3200,3200,28000,1000,100001,0,300,7,0,10,100)
        f=decode(Packet(6,1,data));self.assertEqual(f.values['reason'],'IOUT_OC');self.assertIn('输出过流',format_frame(f))

    def test_upgrade_entire_state_machine_over_binary(self):
        from updater_protocol import perform_upgrade
        from firmware_image import FirmwareImage
        import zlib,hashlib
        data=bytes(range(256))*2
        image=FirmwareImage(Path('mock.bin'),data,'6.2.0',60200,zlib.crc32(data),hashlib.sha256(data).hexdigest())
        class UpgradePort(FakePort):
            def __init__(self):super().__init__();self.received=0;self.total=0
            def write(self,wire):
                self.writes.append(wire);packet=Parser().feed(wire)[0];op=packet.payload[0]
                if op==1:
                    # INFO payload, exactly the same fields as firmware.
                    payload=struct.pack('<4B9HBBIB',6,2,0,2,3200,32000,100,8000,2,20,20,5110,0x4991,16,3,115200,4)
                    reply=encode(4,packet.sequence,payload)
                elif op==2:
                    payload=bytearray(77);struct.pack_into('<H',payload,48,4)
                    reply=encode(5,packet.sequence,payload)
                else:
                    if op==31:self.total=struct.unpack_from('<I',packet.payload,1)[0];detail=b'READY'
                    elif op==32:
                        off=struct.unpack_from('<I',packet.payload,1)[0]
                        if off==self.received:self.received+=len(packet.payload)-5
                        detail=str(self.received).encode()
                    elif op==30:detail=f'{self.received}/{self.total}/0'.encode()
                    elif op==33:detail=b'VERIFIED'
                    elif op==34:detail=b'REBOOTING'
                    else:detail=b'OFF'
                    reply=encode(2,packet.sequence,bytes([op])+detail)
                self.buffer.extend(reply)
        first=UpgradePort();session=SerialSession(first,True)
        def factory(**kwargs):return SerialSession(UpgradePort(),True)
        with patch('updater_protocol.time.sleep',lambda _:None):
            result=perform_upgrade('MOCK',image,factory,lambda *args:None,initial_port=session)
        self.assertEqual(result.new_version,'6.2.0');self.assertEqual(first.received,len(data))
        self.assertFalse(first.is_open);self.assertTrue(all(x.startswith(MAGIC) for x in first.writes))

class DesktopTests(unittest.TestCase):
    def setUp(self):self.b=Bridge()
    def tearDown(self):
        self.b._worker=None;self.b._record.close();self.b._frame_timer.stop();self.b._log_timer.stop();self.b.curve._timer.stop();self.b.deleteLater()
    def test_explicit_transport_and_enumeration_no_open(self):
        b=self.b;b._on_scan_complete([('COM2','COM2  ·  USB CH340','USB / UART',False),('COM8','COM8  ·  标准蓝牙串行','BLUETOOTH SPP',False)])
        self.assertEqual(b.selectedPort,'COM2');self.assertEqual(len(b.ports),1)
        b.selectTransport('wireless');self.assertEqual(b.selectedPort,'COM8')
        b.selectTransport('wired');self.assertEqual(b.selectedPort,'COM2')
        class PortInfo:device='COM7';description='USB CH340';hwid='USB'
        got=[];thread=ProbeScanThread();thread.completed.connect(got.append)
        with patch('serial.Serial',side_effect=AssertionError('scan opened a port')),patch('serial.tools.list_ports.comports',return_value=[PortInfo()]):thread.run()
        self.assertEqual(got[0][0][0],'COM7')
    def test_batching_keeps_all_records(self):
        b=self.b
        class Worker:
            frames=Queue()
            def send(self,c):pass
        b._worker=Worker();changes=[];b.telemetryChanged.connect(lambda:changes.append(1))
        for i in range(10):b._worker.frames.put(parse_line(f'@TEL,t={i*20},vout=3300,vin=28000,setv=3300,seti=100,out=0,fault=NONE'))
        b._drain_frames();self.assertEqual(len(changes),1);self.assertEqual(len(b._telemetry_rows),10)
        b._record.flush();rows=[__import__('json').loads(x) for x in b._record.path.read_text(encoding='utf-8').splitlines()]
        self.assertEqual(sum('csv' in x for x in rows),10)
    def test_calibration_schema5_and_legacy_mapping(self):
        commands=[];c=CurveCalibration(commands.append,lambda:True)
        c.connection_changed(True,'6.2.0');self.assertEqual(c._targets,TARGETS_MV)
        c.on_frame(parse_line('@CURVE,schema=5,mask=1,saved=1,total=16'))
        for i,t in enumerate(TARGETS_MV):c.on_frame(parse_line(f'@CPOINT,id={i},target={t},valid={int(i==0)},actual={t},dac={3000-i},saved=1'))
        self.assertEqual(c.completed,1);self.assertEqual(c.pointRows[0]['label'],'3.2 V');self.assertFalse(c.busy)
        c.connection_changed(False,'—');c.connection_changed(True,'6.1.5');self.assertEqual(c._targets,LEGACY_TARGETS_MV)
        c._timer.stop();c.deleteLater()
    def test_qml_pages_and_resize(self):
        b=self.b;warnings=[];engine=QQmlApplicationEngine();engine.warnings.connect(lambda items:warnings.extend(str(x) for x in items))
        engine.rootContext().setContextProperty('bridge',b);engine.rootContext().setContextProperty('curve',b.curve);engine.rootContext().setContextProperty('pid',b.pid)
        engine.load(QUrl.fromLocalFile(str(Path(__file__).resolve().parents[1]/'qml/Main.qml')))
        self.assertTrue(engine.rootObjects());root=engine.rootObjects()[0]
        b._on_scan_complete([('COM14','COM14  ·  USB-SERIAL CH340','USB / UART',False)])
        b._connected=True;b._firmware='6.2.0';b._connection_text='已连接 XIN Power · COM14'
        b.curve.connection_changed(True,'6.2.0');b.stateChanged.emit()
        b._on_line('@TEL,t=1000,vout=3301,iout=10000,vin=28000,pout=33,temp=300,tempvalid=1,vpp=5,vppvalid=1,hz=500,maxgap=2,setv=3300,seti=1500,out=1,fault=NONE')
        for page in (0,2,4):
            root.setProperty('activePage',page)
            for i in range(5):b._log('接收 | '+format_frame(parse_line('@ACK,cmd=SET_V,detail=3300')))
            b._flush_log_view();loop=QEventLoop();QTimer.singleShot(150,loop.quit);loop.exec()
            image=root.grabWindow();self.assertFalse(image.isNull());image.save(str(Path(__file__).with_name(f'page_620_{page}.png')))
        root.setProperty('width',1050);root.setProperty('height',700);APP.processEvents()
        self.assertEqual(warnings,[]);root.close();engine.deleteLater()

if __name__=='__main__':unittest.main(verbosity=2)
