"""Generate the OFL licensed XIN UI Heiti bitmap subset from Source Han Sans.

The unmodified source font and OFL notice are in ThirdParty/SourceHanSans.
The derived bitmap is named XIN UI Heiti and remains under OFL-1.1.
"""
from pathlib import Path
import argparse
import re
from PIL import Image, ImageDraw, ImageFont

root = Path(__file__).resolve().parents[1]
parser = argparse.ArgumentParser()
parser.add_argument('--font', default=str(root / 'ThirdParty/SourceHanSans/SourceHanSansCN-Regular.otf'))
args = parser.parse_args()
source = (root / 'Core/SRC/ui_page.c').read_text(encoding='utf-8')
chars = set(chr(i) for i in range(32, 127))
for literal in re.findall(r'"([^"\n]*)"', source):
    chars.update(ch for ch in literal if ord(ch) >= 128)
chars = sorted(chars, key=ord)
tables = []
for size in (14, 18):
    font = ImageFont.truetype(args.font, size)
    data, glyphs = [], []
    for ch in chars:
        width = max(1, round(font.getlength(ch)))
        im = Image.new('1', (width, size))
        # Common baseline retains punctuation alignment alongside Chinese text.
        ImageDraw.Draw(im).text((0, size - 2), ch, font=font, fill=1, anchor='ls')
        stride, offset = (width + 7) // 8, len(data)
        for y in range(size):
            for col in range(stride):
                value = sum(0x80 >> bit for bit in range(8)
                            if col * 8 + bit < width and im.getpixel((col * 8 + bit, y)))
                data.append(value)
        glyphs.append(f'{{0x{ord(ch):04X}U,{width}U,{offset}U}}')
    tables += [f'static const LCD_HeitiGlyph_t s_heiti_{size}[]={{' + ','.join(glyphs) + '};',
               f'static const uint8_t s_heiti_bits_{size}[]={{' + ','.join(map(str, data)) + '};']
notice = ('/* XIN UI Heiti bitmap subset, derived from Source Han Sans SC.\n'
          ' * Copyright 2014-2025 Adobe. Derived bitmap: XIN Power contributors.\n'
          ' * SIL Open Font License 1.1; see ThirdParty/SourceHanSans/OFL.txt.\n'
          ' * Generated by Tools/generate_heiti_font.py; packed 1bpp. */\n')
(root / 'Core/SRC/lcd_font_heiti.inc').write_text(notice + '\n'.join(tables) + '\n', encoding='utf-8')
print(f'Generated XIN UI Heiti: {len(chars)} glyphs at 14/18 pixels')
