#ifndef XIN_POWER_FIRMWARE_VERSION_H
#define XIN_POWER_FIRMWARE_VERSION_H

/* One source of truth for the local settings page and USB INFO reply. */
#define XIN_POWER_FIRMWARE_MAJOR 6
#define XIN_POWER_FIRMWARE_MINOR 2
#define XIN_POWER_FIRMWARE_PATCH 3
#define XIN_POWER_STRINGIFY_INNER(value) #value
#define XIN_POWER_STRINGIFY(value) XIN_POWER_STRINGIFY_INNER(value)
#define XIN_POWER_FIRMWARE_VERSION \
  XIN_POWER_STRINGIFY(XIN_POWER_FIRMWARE_MAJOR) "." \
  XIN_POWER_STRINGIFY(XIN_POWER_FIRMWARE_MINOR) "." \
  XIN_POWER_STRINGIFY(XIN_POWER_FIRMWARE_PATCH)
#define XIN_POWER_PROTOCOL_VERSION "5"
#define XIN_POWER_HARDWARE_ID "PY32F403_V2"

#endif
